name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (Python ${{matrix.version}})
    strategy:
      matrix:
        version: [39, 313] # Test on oldest and newest versions used in wally-package-install.sh
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set Python version
      run: sed -i '/^target-version/c\target-version = "py${{matrix.version}}"' .ruff.toml

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Ensure pre-commit checks pass
      run: uv tool run pre-commit run --all-files --show-diff-on-failure --color=always
